# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Book(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, author: str=None, year: int=None, price: float=None):  # noqa: E501
        """Book - a model defined in Swagger

        :param id: The id of this Book.  # noqa: E501
        :type id: int
        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param author: The author of this Book.  # noqa: E501
        :type author: str
        :param year: The year of this Book.  # noqa: E501
        :type year: int
        :param price: The price of this Book.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'author': str,
            'year': int,
            'price': float
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author',
            'year': 'year',
            'price': 'price'
        }
        self._id = id
        self._title = title
        self._author = author
        self._year = year
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Book.

        ID duy nhất của sách  # noqa: E501

        :return: The id of this Book.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Book.

        ID duy nhất của sách  # noqa: E501

        :param id: The id of this Book.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Book.

        Tên sách  # noqa: E501

        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.

        Tên sách  # noqa: E501

        :param title: The title of this Book.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this Book.

        Tác giả  # noqa: E501

        :return: The author of this Book.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Book.

        Tác giả  # noqa: E501

        :param author: The author of this Book.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def year(self) -> int:
        """Gets the year of this Book.

        Năm xuất bản  # noqa: E501

        :return: The year of this Book.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this Book.

        Năm xuất bản  # noqa: E501

        :param year: The year of this Book.
        :type year: int
        """

        self._year = year

    @property
    def price(self) -> float:
        """Gets the price of this Book.

        Giá sách  # noqa: E501

        :return: The price of this Book.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Book.

        Giá sách  # noqa: E501

        :param price: The price of this Book.
        :type price: float
        """

        self._price = price
