# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, success: bool=None, data: User=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param success: The success of this InlineResponse2002.  # noqa: E501
        :type success: bool
        :param data: The data of this InlineResponse2002.  # noqa: E501
        :type data: User
        """
        self.swagger_types = {
            'success': bool,
            'data': User
        }

        self.attribute_map = {
            'success': 'success',
            'data': 'data'
        }
        self._success = success
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this InlineResponse2002.


        :return: The success of this InlineResponse2002.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this InlineResponse2002.


        :param success: The success of this InlineResponse2002.
        :type success: bool
        """

        self._success = success

    @property
    def data(self) -> User:
        """Gets the data of this InlineResponse2002.


        :return: The data of this InlineResponse2002.
        :rtype: User
        """
        return self._data

    @data.setter
    def data(self, data: User):
        """Sets the data of this InlineResponse2002.


        :param data: The data of this InlineResponse2002.
        :type data: User
        """

        self._data = data
