# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class InlineResponse201Data(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: User=None, access_token: str=None, refresh_token: str=None):  # noqa: E501
        """InlineResponse201Data - a model defined in Swagger

        :param user: The user of this InlineResponse201Data.  # noqa: E501
        :type user: User
        :param access_token: The access_token of this InlineResponse201Data.  # noqa: E501
        :type access_token: str
        :param refresh_token: The refresh_token of this InlineResponse201Data.  # noqa: E501
        :type refresh_token: str
        """
        self.swagger_types = {
            'user': User,
            'access_token': str,
            'refresh_token': str
        }

        self.attribute_map = {
            'user': 'user',
            'access_token': 'access_token',
            'refresh_token': 'refresh_token'
        }
        self._user = user
        self._access_token = access_token
        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_data of this InlineResponse201Data.  # noqa: E501
        :rtype: InlineResponse201Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> User:
        """Gets the user of this InlineResponse201Data.


        :return: The user of this InlineResponse201Data.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this InlineResponse201Data.


        :param user: The user of this InlineResponse201Data.
        :type user: User
        """

        self._user = user

    @property
    def access_token(self) -> str:
        """Gets the access_token of this InlineResponse201Data.

        Access token (JWT)  # noqa: E501

        :return: The access_token of this InlineResponse201Data.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this InlineResponse201Data.

        Access token (JWT)  # noqa: E501

        :param access_token: The access_token of this InlineResponse201Data.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this InlineResponse201Data.

        Refresh token (JWT, dùng để lấy access token mới)  # noqa: E501

        :return: The refresh_token of this InlineResponse201Data.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this InlineResponse201Data.

        Refresh token (JWT, dùng để lấy access token mới)  # noqa: E501

        :param refresh_token: The refresh_token of this InlineResponse201Data.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token
