# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, success: bool=None, message: str=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param success: The success of this InlineResponse2004.  # noqa: E501
        :type success: bool
        :param message: The message of this InlineResponse2004.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'success': bool,
            'message': str
        }

        self.attribute_map = {
            'success': 'success',
            'message': 'message'
        }
        self._success = success
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this InlineResponse2004.


        :return: The success of this InlineResponse2004.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this InlineResponse2004.


        :param success: The success of this InlineResponse2004.
        :type success: bool
        """

        self._success = success

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2004.


        :return: The message of this InlineResponse2004.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2004.


        :param message: The message of this InlineResponse2004.
        :type message: str
        """

        self._message = message
