# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, success: bool=None, access_token: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param success: The success of this InlineResponse2001.  # noqa: E501
        :type success: bool
        :param access_token: The access_token of this InlineResponse2001.  # noqa: E501
        :type access_token: str
        """
        self.swagger_types = {
            'success': bool,
            'access_token': str
        }

        self.attribute_map = {
            'success': 'success',
            'access_token': 'access_token'
        }
        self._success = success
        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this InlineResponse2001.


        :return: The success of this InlineResponse2001.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this InlineResponse2001.


        :param success: The success of this InlineResponse2001.
        :type success: bool
        """

        self._success = success

    @property
    def access_token(self) -> str:
        """Gets the access_token of this InlineResponse2001.

        Access token mới  # noqa: E501

        :return: The access_token of this InlineResponse2001.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this InlineResponse2001.

        Access token mới  # noqa: E501

        :param access_token: The access_token of this InlineResponse2001.
        :type access_token: str
        """

        self._access_token = access_token
