# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response201_data import InlineResponse201Data  # noqa: F401,E501
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, success: bool=None, message: str=None, data: InlineResponse201Data=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param success: The success of this InlineResponse201.  # noqa: E501
        :type success: bool
        :param message: The message of this InlineResponse201.  # noqa: E501
        :type message: str
        :param data: The data of this InlineResponse201.  # noqa: E501
        :type data: InlineResponse201Data
        """
        self.swagger_types = {
            'success': bool,
            'message': str,
            'data': InlineResponse201Data
        }

        self.attribute_map = {
            'success': 'success',
            'message': 'message',
            'data': 'data'
        }
        self._success = success
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this InlineResponse201.


        :return: The success of this InlineResponse201.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this InlineResponse201.


        :param success: The success of this InlineResponse201.
        :type success: bool
        """

        self._success = success

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse201.


        :return: The message of this InlineResponse201.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse201.


        :param message: The message of this InlineResponse201.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> InlineResponse201Data:
        """Gets the data of this InlineResponse201.


        :return: The data of this InlineResponse201.
        :rtype: InlineResponse201Data
        """
        return self._data

    @data.setter
    def data(self, data: InlineResponse201Data):
        """Sets the data of this InlineResponse201.


        :param data: The data of this InlineResponse201.
        :type data: InlineResponse201Data
        """

        self._data = data
